### PR TITLE
fix by Felix Kurth <fku@inmedias.it> to address slow page loads with >70k users

### PR DESCRIPTION
**Pull request by lirantal**
Quoting Felix:

> Dear Mr Tal,
> 
> Our company uses its Daloradius software with about 70,000 users. Because a lot of very slow sql queries we have made some adjustments to increase the performance. We would be very happy if you would install this in future versions.
> 
> The changes apply to both the queries for counting and for the output of the data are responsible.

This PR addresses the issue by applying the patches he sent me.

### CODE REVIEW

**Comment by lirantal** [comment]
btw @MiguelVis, do you want to review the changes here?
I couldn't test it locally, but if you have a setup ready then this PR seems like a promising performance fix.

**Comment by MiguelVis** [comment]
@lirantal 

Ok, I will look at this asap.

**Comment by lirantal** [comment]
@filippolauria do you maybe want to try this PR out?
It seems to be a really big performance improvement fix but it needs a bit of testing so maybe you can confirm this works ok and then land the changes?

**Review by filippolauria — COMMENTED** [review]
The fixes look syntactically good to me.
Anyway, indexes can mitigate queries slowness, too.

**Comment by filippolauria** [comment]
This has been addressed in other PRs.

**Pull request closed without merging**
