### PR TITLE
fix display issue and some error in PHP7

### PR DESCRIPTION
**Pull request by terencechuen**
1. fix display dislocation in login page;
2. fix "copyright1" not show issue at header in some pages;
3. use explode replacement split adapt to php7

### CODE REVIEW

**Comment by lirantal** [comment]
Hi @terencechuen, why did you close this Pull Request?

**Comment by terencechuen** [comment]
hi @lirantal 
sorry, I should let it open,didn't I?
I think I should read user manual about github.
I still reprogramming some pages.

**Comment by lirantal** [comment]
Yes we can leave the PR open until you're done making changes.
We should also update the PR to merge the changes not to master branch here but to another PHP7 branch because we're just testing this out until it's stable and complete.

For now let's focus on making daloRADIUS work, and I can help with the Git/GitHub stuff later.

Much appreciate all the help here @terencechuen, great job!

**Comment by terencechuen** [comment]
I get it.
I will make sure daloradius working properly with freeRADIUS 3.
If I have problem I can't solve, I will seeking help here.

**Comment by lirantal** [comment]
@terencechuen how's it going with the PHP7 work? the master branch should be ready for PHP7 including my new PR to fix the deprecated `split` function in PR #8 which waits to be merged to master after someone tests it.

**Pull request closed without merging**
