### PR TITLE
Add Arabic Language

### PR DESCRIPTION
**Pull request by momothefox**
Adding Arabic Translation for daloradius

### CODE REVIEW

**Comment by filippolauria** [comment]
Also, consider to properly update the array [$valid_languages in library/validation.php](https://github.com/lirantal/daloradius/blob/028ed29bb10db316ddce5c693aface64f122f660/library/validation.php#L119).

**Comment by filippolauria** [comment]
> Thanks for the big effort.

No problem man :)

> I will continue Translating every thing.

Great!
> but notice that the subnav menu is static. there are no variables for it.
> so it is not translating.
>
> Also can you consider LTR option . so right to left language can switch page direction ?
I know. There's lot of stuff to do.

Please also consider to address the "issues" I have pointed to you out using inline comments to your committed files.

**Comment by momothefox** [comment]
> Please also consider to address the "issues" I have pointed to you out using inline comments to your committed files

Sorry how to do that?

**Comment by filippolauria** [comment]
I'll include that, here:
Line 27: the strpos function should check for '/lang/ar.php' (not for '/lang/en.php')
Line 18-21: Change the description and add your name in the authors (if you wish)
Line 1821-1829: Strip all HTML tags here

**Comment by momothefox** [comment]
Let me ask you. 
Can i Use Slang Language? 
somehow it is Hard to find Easy Arabic words for some expressions.
Or i should stick to Standard Arabic?

**Comment by filippolauria** [comment]
I don't know.
As a general rule of thumb, I think you should stick to terms understandable to most Arab users, but that's just my opinion.

**Pull request closed without merging**
