### PR TITLE
Dockerfile-freeradius + init-freeradius.sh

### PR DESCRIPTION
**Pull request by ashadebi**
Create new Dockerfile-freeradius and init-freeradius.sh

### CODE REVIEW

**Comment by lirantal** [comment]
thanks ❤️

**Comment by frauhottelmann** [comment]
Hi @ashadebi,
while cleaing up the Dockerfiles I noticed in yours, that you're setting ``ENV mysql_pass ""``, but it isn't used anywhere.
https://github.com/lirantal/daloradius/blob/c95e13a365a09ebb5c776d8515fdfc6e605b6339/Dockerfile-freeradius#L22
But in the initfile you're using ``$MYSQLTMPROOT``
https://github.com/lirantal/daloradius/blob/c95e13a365a09ebb5c776d8515fdfc6e605b6339/init-freeradius.sh#L7

Is that intentional? :wink:

**Comment by ashadebi** [comment]
hi @frauhottelmann ,

oh that missing line , my mistake merge it from my Dockerfile. Thanks for the correction. 
Have you already have the Dockerfile update at that line?

**Comment by frauhottelmann** [comment]
No, I haven't updated that line. Will you create a pull request?

**Pull request merged**
