### PR TITLE
Added freeradius-utils and cron to dockerfile

### PR DESCRIPTION
**Pull request by AxeyOS**
User connectivity test was not working

### CODE REVIEW

**Comment by lirantal** [comment]
Thanks @AxeyOS 

WDYT instead about creating a docker-compose to include freeradius image as a server in a different container? 

Next good step would be to create our own freeradius image that uses the config from daloradius project, like the sql counters enabled by default, etc.

**Comment by AxeyOS** [comment]
> Thanks @AxeyOS
> 
> WDYT instead about creating a docker-compose to include freeradius image as a server in a different container?
> 
> Next good step would be to create our own freeradius image that uses the config from daloradius project, like the sql counters enabled by default, etc.

**Comment by AxeyOS** [comment]
I think it's a good idea, i will make a pull request in a few weeks with some production kubernetes yaml files i'm writting, with daloradius and freeradius well isolated from each other


sorry i unintentionally closed this pull

**Comment by lirantal** [comment]
Ok so in this case, why do we need to add `freeradius-utils` and `cron` to the dockerfile? What would adding them benefit?

**Comment by AxeyOS** [comment]
> Ok so in this case, why do we need to add `freeradius-utils` and `cron` to the dockerfile? What would adding them benefit?

without freeradius-utils we can't send disconnect packets and do connection tests, and without cron the script that removes stale sessions won't run

**Comment by lirantal** [comment]
Right, and we need that ;-)
Thanks for the PR!

**Pull request merged**
