### PR TITLE
update language line 796

### PR DESCRIPTION
**Pull request by wellesximenes**
Greetings I liked the software, I am translating I am already on line 796 I would like to donate to the community I intend to end this weekend

### CODE REVIEW

**Comment by lirantal** [comment]
Sounds wonderful @wellesximenes, thank you.
Ping me again when it's ready and I'll merge it.

**Comment by wellesximenes** [comment]
Friend completed a translation

**Comment by lirantal** [comment]
@wellesximenes let me know when it's final? :)
I see you pushed a few more commits

**Comment by wellesximenes** [comment]
Ok

**Comment by wellesximenes** [comment]
correct sorry

**Comment by lirantal** [comment]
feel free to @MiguelVis merge away
@wellesximenes great stuff, thank you!

**Pull request merged**
