### PR TITLE
Update fr3-mysql-freeradius.sql

### PR DESCRIPTION
**Pull request by omelendres**
Update sql import of module sqlippool
Resolve issues with field expiry_time with NULL value

### CODE REVIEW

**Comment by filippolauria** [comment]
Hi @omelendres 
thank you for your contribution.

With the changes you made, old versions of MySQL won't accept this schema.
A solution can still be found though: check [this](https://stackoverflow.com/questions/168736/how-do-you-set-a-default-value-for-a-mysql-datetime-column) out.
Also, please don't change the case of SQL statements.

**Comment by omelendres** [comment]
Hi @filippolauria, thank you for revieweng my request,
The schema change for the sqlippool table applies only to freeradius version 3 (fr3 on the name of the file). 
The schema changes are proposed on the source code of freeradius,
https://github.com/FreeRADIUS/freeradius-server/blob/v3.0.x/raddb/mods-config/sql/ippool/mysql/schema.sql

**Comment by filippolauria** [comment]
I see. I guess FreeRADIUS 3.x cannot be installed on older MySQL backends.
Anyway, even though MySQL statements are case insensitive, for readability reason use upper case for them.
It is a little effort, but it keeps fr3-mysql-freeradius a little bit tidier.

**Comment by omelendres** [comment]
Agree. Removed also the InnodB which should be the default engine

**Pull request merged**
